services:
  php:
    build:
      context: .
      args:
          - USER_UID=1000
          - USER_GID=1000
    volumes:
      - "./app:/var/www/html"
      - "./artifacts/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - "./artifacts/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./app/public:/var/www/html/public"
