services:
  php:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - "./app:/var/www/html"
      - "./artifacts/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    volumes:
      - "./artifacts/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./app/public:/var/www/html/public"
