parameters:
    container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\SharedKernel\Es\Contract\EventSourceStoreInterface:
        '@App\SharedKernel\Es\Implementation\EventSourceStoreDbal'
